# Generated by Django 5.2.8 on 2025-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_booking_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
